"""Py Spark Schemas (StructType) for data files"""

from pyspark.sql.types import (
    StructType, StructField, StringType, IntegerType, FloatType, TimestampType
)


RATIO9_SCHEMA = StructType(
    [
        StructField("index", StringType(), False),
        StructField("ratio_key", StringType(), False),
        StructField("start_date", TimestampType(), False),
        StructField("end_date", TimestampType(), False),
        StructField("ratio1", FloatType(), True),
        StructField("ratio2", FloatType(), True),
        StructField("ratio3", FloatType(), True),
        StructField("ratio4", FloatType(), True),
        StructField("ratio5", FloatType(), True),
        StructField("ratio6", FloatType(), True),
        StructField("ratio7", FloatType(), True),
        StructField("ratio8", FloatType(), True),
        StructField("ratio9", FloatType(), True),
        StructField("ratio10", FloatType(), True),
        StructField("ratio11", FloatType(), True),
        StructField("ratio12", FloatType(), True),
        StructField("ratio13", FloatType(), True),
        StructField("ratio14", FloatType(), True),
        StructField("ratio15", FloatType(), True),
        StructField("ratio16", FloatType(), True),
        StructField("ratio17", FloatType(), True),
        StructField("ratio18", FloatType(), True),
        StructField("ratio19", FloatType(), True),
        StructField("ratio20", FloatType(), True),
        StructField("ratio21", FloatType(), True),
        StructField("ratio22", FloatType(), True),
        StructField("ratio23", FloatType(), True),
        StructField("ratio24", FloatType(), True),
        StructField("ratio25", FloatType(), True),
        StructField("ratio26", FloatType(), True),
        StructField("ratio27", FloatType(), True),
        StructField("ratio28", FloatType(), True),
        StructField("ratio29", FloatType(), True),
        StructField("ratio30", FloatType(), True),
        StructField("ratio31", FloatType(), True),
        StructField("ratio32", FloatType(), True),
        StructField("ratio33", FloatType(), True),
        StructField("ratio34", FloatType(), True),
        StructField("ratio35", FloatType(), True),
        StructField("ratio36", FloatType(), True),
        StructField("ratio37", FloatType(), True),
        StructField("dratio1", FloatType(), True),
        StructField("dratio2", FloatType(), True),
        StructField("dratio3", FloatType(), True),
        StructField("dratio4", FloatType(), True),
        StructField("dratio5", FloatType(), True),
        StructField("dratio6", FloatType(), True),
        StructField("dratio7", FloatType(), True),
        StructField("dratio8", FloatType(), True),
        StructField("dratio9", FloatType(), True),
        StructField("dratio10", FloatType(), True),
        StructField("dratio11", FloatType(), True),
        StructField("dratio12", FloatType(), True),
        StructField("dratio13", FloatType(), True),
        StructField("dratio14", FloatType(), True),
        StructField("dratio15", FloatType(), True),
        StructField("dratio16", FloatType(), True),
        StructField("dratio17", FloatType(), True),
        StructField("dratio18", FloatType(), True),
        StructField("dratio19", FloatType(), True),
        StructField("dratio20", FloatType(), True),
        StructField("dratio21", FloatType(), True),
        StructField("dratio22", FloatType(), True),
        StructField("dratio23", FloatType(), True),
        StructField("dratio24", FloatType(), True),
        StructField("dratio25", FloatType(), True),
        StructField("dratio26", FloatType(), True),
        StructField("dratio27", FloatType(), True),
        StructField("dratio28", FloatType(), True),
        StructField("dratio29", FloatType(), True),
        StructField("dratio30", FloatType(), True),
        StructField("dratio31", FloatType(), True),
        StructField("dratio32", FloatType(), True),
        StructField("dratio33", FloatType(), True),
        StructField("dratio34", FloatType(), True),
        StructField("dratio35", FloatType(), True),
        StructField("dratio36", FloatType(), True),
        StructField("dratio37", FloatType(), True),
        StructField("valid_flag", IntegerType(), True),
    ]
)


HOSPITL_ENCOUNTER_SCHEMA = StructType(
    [
        StructField("TS", StringType(), False),
        StructField("TestCaseName", StringType(), False),
        StructField("type", StringType(), True),
        StructField("record_identifier", StringType(), True),
        StructField("facility_id", StringType(), True),
        StructField("fac_medicare_id", StringType(), True),
        StructField("age_in_years", StringType(), True),
        StructField("age_in_months", StringType(), True),
        StructField("age_in_days", StringType(), True),
        StructField("birth_date", StringType(), True),
        StructField("sex", StringType(), True),
        StructField("discharge_status", StringType(), True),
        StructField("admit_date", StringType(), True),
        StructField("discharge_date", StringType(), True),
        StructField("los", StringType(), True),
        StructField("birth_weight", StringType(), True),
        StructField("prin_payer", StringType(), True),
        StructField("race", StringType(), True),
        StructField("admit_type", StringType(), True),
        StructField("dx1", StringType(), True),
        StructField("dx2", StringType(), True),
        StructField("dx3", StringType(), True),
        StructField("dx4", StringType(), True),
        StructField("dx5", StringType(), True),
        StructField("dx6", StringType(), True),
        StructField("dx7", StringType(), True),
        StructField("dx8", StringType(), True),
        StructField("dx9", StringType(), True),
        StructField("dx10", StringType(), True),
        StructField("dx11", StringType(), True),
        StructField("dx12", StringType(), True),
        StructField("dx13", StringType(), True),
        StructField("dx14", StringType(), True),
        StructField("dx15", StringType(), True),
        StructField("dx16", StringType(), True),
        StructField("dx17", StringType(), True),
        StructField("dx18", StringType(), True),
        StructField("dx19", StringType(), True),
        StructField("dx20", StringType(), True),
        StructField("dx21", StringType(), True),
        StructField("dx22", StringType(), True),
        StructField("dx23", StringType(), True),
        StructField("dx24", StringType(), True),
        StructField("dx25", StringType(), True),
        StructField("dx26", StringType(), True),
        StructField("dx27", StringType(), True),
        StructField("dx28", StringType(), True),
        StructField("dx29", StringType(), True),
        StructField("dx30", StringType(), True),
        StructField("dx31", StringType(), True),
        StructField("dx32", StringType(), True),
        StructField("dx33", StringType(), True),
        StructField("dx34", StringType(), True),
        StructField("dx35", StringType(), True),
        StructField("dx36", StringType(), True),
        StructField("dx37", StringType(), True),
        StructField("dx38", StringType(), True),
        StructField("dx39", StringType(), True),
        StructField("dx40", StringType(), True),
        StructField("dx41", StringType(), True),
        StructField("dx42", StringType(), True),
        StructField("dx43", StringType(), True),
        StructField("dx44", StringType(), True),
        StructField("dx45", StringType(), True),
        StructField("dx46", StringType(), True),
        StructField("dx47", StringType(), True),
        StructField("dx48", StringType(), True),
        StructField("dx49", StringType(), True),
        StructField("dx50", StringType(), True),
        StructField("proc1", StringType(), True),
        StructField("proc2", StringType(), True),
        StructField("proc3", StringType(), True),
        StructField("proc4", StringType(), True),
        StructField("proc5", StringType(), True),
        StructField("proc6", StringType(), True),
        StructField("proc7", StringType(), True),
        StructField("proc8", StringType(), True),
        StructField("proc9", StringType(), True),
        StructField("proc10", StringType(), True),
        StructField("proc11", StringType(), True),
        StructField("proc12", StringType(), True),
        StructField("proc13", StringType(), True),
        StructField("proc14", StringType(), True),
        StructField("proc15", StringType(), True),
        StructField("proc16", StringType(), True),
        StructField("proc17", StringType(), True),
        StructField("proc18", StringType(), True),
        StructField("proc19", StringType(), True),
        StructField("proc20", StringType(), True),
        StructField("proc21", StringType(), True),
        StructField("proc22", StringType(), True),
        StructField("proc23", StringType(), True),
        StructField("proc24", StringType(), True),
        StructField("proc25", StringType(), True),
        StructField("proc26", StringType(), True),
        StructField("proc27", StringType(), True),
        StructField("proc28", StringType(), True),
        StructField("proc29", StringType(), True),
        StructField("proc30", StringType(), True),
        StructField("proc31", StringType(), True),
        StructField("proc32", StringType(), True),
        StructField("proc33", StringType(), True),
        StructField("proc34", StringType(), True),
        StructField("proc35", StringType(), True),
        StructField("proc36", StringType(), True),
        StructField("proc37", StringType(), True),
        StructField("proc38", StringType(), True),
        StructField("proc39", StringType(), True),
        StructField("proc40", StringType(), True),
        StructField("proc41", StringType(), True),
        StructField("proc42", StringType(), True),
        StructField("proc43", StringType(), True),
        StructField("proc44", StringType(), True),
        StructField("proc45", StringType(), True),
        StructField("proc46", StringType(), True),
        StructField("proc47", StringType(), True),
        StructField("proc48", StringType(), True),
        StructField("proc49", StringType(), True),
        StructField("proc50", StringType(), True),
        StructField("proc1_date", StringType(), True),
        StructField("proc2_date", StringType(), True),
        StructField("proc3_date", StringType(), True),
        StructField("proc4_date", StringType(), True),
        StructField("proc5_date", StringType(), True),
        StructField("proc6_date", StringType(), True),
        StructField("proc7_date", StringType(), True),
        StructField("proc8_date", StringType(), True),
        StructField("proc9_date", StringType(), True),
        StructField("proc10_date", StringType(), True),
        StructField("proc11_date", StringType(), True),
        StructField("proc12_date", StringType(), True),
        StructField("proc13_date", StringType(), True),
        StructField("proc14_date", StringType(), True),
        StructField("proc15_date", StringType(), True),
        StructField("proc16_date", StringType(), True),
        StructField("proc17_date", StringType(), True),
        StructField("proc18_date", StringType(), True),
        StructField("proc19_date", StringType(), True),
        StructField("proc20_date", StringType(), True),
        StructField("proc21_date", StringType(), True),
        StructField("proc22_date", StringType(), True),
        StructField("proc23_date", StringType(), True),
        StructField("proc24_date", StringType(), True),
        StructField("proc25_date", StringType(), True),
        StructField("proc26_date", StringType(), True),
        StructField("proc27_date", StringType(), True),
        StructField("proc28_date", StringType(), True),
        StructField("proc29_date", StringType(), True),
        StructField("proc30_date", StringType(), True),
        StructField("proc31_date", StringType(), True),
        StructField("proc32_date", StringType(), True),
        StructField("proc33_date", StringType(), True),
        StructField("proc34_date", StringType(), True),
        StructField("proc35_date", StringType(), True),
        StructField("proc36_date", StringType(), True),
        StructField("proc37_date", StringType(), True),
        StructField("proc38_date", StringType(), True),
        StructField("proc39_date", StringType(), True),
        StructField("proc40_date", StringType(), True),
        StructField("proc41_date", StringType(), True),
        StructField("proc42_date", StringType(), True),
        StructField("proc43_date", StringType(), True),
        StructField("proc44_date", StringType(), True),
        StructField("proc45_date", StringType(), True),
        StructField("proc46_date", StringType(), True),
        StructField("proc47_date", StringType(), True),
        StructField("proc48_date", StringType(), True),
        StructField("proc49_date", StringType(), True),
        StructField("proc50_date", StringType(), True),
        StructField("total_chg", StringType(), True),
        StructField("admit_source", StringType(), True),
        StructField("ed_obs_flag", StringType(), True),
        StructField("chg1", StringType(), True),
        StructField("chg2", StringType(), True),
        StructField("chg3", StringType(), True),
        StructField("chg4", StringType(), True),
        StructField("chg5", StringType(), True),
        StructField("chg6", StringType(), True),
        StructField("chg7", StringType(), True),
        StructField("chg8", StringType(), True),
        StructField("chg9", StringType(), True),
        StructField("chg10", StringType(), True),
        StructField("chg11", StringType(), True),
        StructField("chg12", StringType(), True),
        StructField("chg13", StringType(), True),
        StructField("chg14", StringType(), True),
        StructField("chg15", StringType(), True),
        StructField("chg16", StringType(), True),
        StructField("chg17", StringType(), True),
        StructField("chg18", StringType(), True),
        StructField("chg19", StringType(), True),
        StructField("chg20", StringType(), True),
        StructField("chg21", StringType(), True),
        StructField("chg22", StringType(), True),
        StructField("chg23", StringType(), True),
        StructField("chg24", StringType(), True),
        StructField("chg25", StringType(), True),
        StructField("chg26", StringType(), True),
        StructField("chg27", StringType(), True),
        StructField("chg28", StringType(), True),
        StructField("chg29", StringType(), True),
        StructField("chg30", StringType(), True),
        StructField("chg31", StringType(), True),
        StructField("chg32", StringType(), True),
        StructField("chg33", StringType(), True),
        StructField("chg34", StringType(), True),
        StructField("chg35", StringType(), True),
        StructField("chg36", StringType(), True),
        StructField("chg37", StringType(), True),
        StructField("chg38", StringType(), True),
        StructField("chg39", StringType(), True),
        StructField("chg40", StringType(), True),
        StructField("chg41", StringType(), True),
        StructField("chg42", StringType(), True),
        StructField("chg43", StringType(), True),
        StructField("chg44", StringType(), True),
        StructField("chg45", StringType(), True),
        StructField("chg46", StringType(), True),
        StructField("chg47", StringType(), True),
        StructField("chg48", StringType(), True),
        StructField("chg49", StringType(), True),
        StructField("chg50", StringType(), True),
        StructField("rev_code1", IntegerType(), True),
        StructField("rev_code2", IntegerType(), True),
        StructField("rev_code3", IntegerType(), True),
        StructField("rev_code4", IntegerType(), True),
        StructField("rev_code5", IntegerType(), True),
        StructField("rev_code6", IntegerType(), True),
        StructField("rev_code7", IntegerType(), True),
        StructField("rev_code8", IntegerType(), True),
        StructField("rev_code9", IntegerType(), True),
        StructField("rev_code10", IntegerType(), True),
        StructField("rev_code11", IntegerType(), True),
        StructField("rev_code12", IntegerType(), True),
        StructField("rev_code13", IntegerType(), True),
        StructField("rev_code14", IntegerType(), True),
        StructField("rev_code15", IntegerType(), True),
        StructField("rev_code16", IntegerType(), True),
        StructField("rev_code17", IntegerType(), True),
        StructField("rev_code18", IntegerType(), True),
        StructField("rev_code19", IntegerType(), True),
        StructField("rev_code20", IntegerType(), True),
        StructField("rev_code21", IntegerType(), True),
        StructField("rev_code22", IntegerType(), True),
        StructField("rev_code23", IntegerType(), True),
        StructField("rev_code24", IntegerType(), True),
        StructField("rev_code25", IntegerType(), True),
        StructField("rev_code26", IntegerType(), True),
        StructField("rev_code27", IntegerType(), True),
        StructField("rev_code28", IntegerType(), True),
        StructField("rev_code29", IntegerType(), True),
        StructField("rev_code30", IntegerType(), True),
        StructField("rev_code31", IntegerType(), True),
        StructField("rev_code32", IntegerType(), True),
        StructField("rev_code33", IntegerType(), True),
        StructField("rev_code34", IntegerType(), True),
        StructField("rev_code35", IntegerType(), True),
        StructField("rev_code36", IntegerType(), True),
        StructField("rev_code37", IntegerType(), True),
        StructField("rev_code38", IntegerType(), True),
        StructField("rev_code39", IntegerType(), True),
        StructField("rev_code40", IntegerType(), True),
        StructField("rev_code41", IntegerType(), True),
        StructField("rev_code42", IntegerType(), True),
        StructField("rev_code43", IntegerType(), True),
        StructField("rev_code44", IntegerType(), True),
        StructField("rev_code45", IntegerType(), True),
        StructField("rev_code46", IntegerType(), True),
        StructField("rev_code47", IntegerType(), True),
        StructField("rev_code48", IntegerType(), True),
        StructField("rev_code49", IntegerType(), True),
        StructField("rev_code50", IntegerType(), True),
        StructField("poa1", StringType(), True),
        StructField("poa2", StringType(), True),
        StructField("poa3", StringType(), True),
        StructField("poa4", StringType(), True),
        StructField("poa5", StringType(), True),
        StructField("poa6", StringType(), True),
        StructField("poa7", StringType(), True),
        StructField("poa8", StringType(), True),
        StructField("poa9", StringType(), True),
        StructField("poa10", StringType(), True),
        StructField("poa11", StringType(), True),
        StructField("poa12", StringType(), True),
        StructField("poa13", StringType(), True),
        StructField("poa14", StringType(), True),
        StructField("poa15", StringType(), True),
        StructField("poa16", StringType(), True),
        StructField("poa17", StringType(), True),
        StructField("poa18", StringType(), True),
        StructField("poa19", StringType(), True),
        StructField("poa20", StringType(), True),
        StructField("poa21", StringType(), True),
        StructField("poa22", StringType(), True),
        StructField("poa23", StringType(), True),
        StructField("poa24", StringType(), True),
        StructField("poa25", StringType(), True),
        StructField("poa26", StringType(), True),
        StructField("poa27", StringType(), True),
        StructField("poa28", StringType(), True),
        StructField("poa29", StringType(), True),
        StructField("poa30", StringType(), True),
        StructField("poa31", StringType(), True),
        StructField("poa32", StringType(), True),
        StructField("poa33", StringType(), True),
        StructField("poa34", StringType(), True),
        StructField("poa35", StringType(), True),
        StructField("poa36", StringType(), True),
        StructField("poa37", StringType(), True),
        StructField("poa38", StringType(), True),
        StructField("poa39", StringType(), True),
        StructField("poa40", StringType(), True),
        StructField("poa41", StringType(), True),
        StructField("poa42", StringType(), True),
        StructField("poa43", StringType(), True),
        StructField("poa44", StringType(), True),
        StructField("poa45", StringType(), True),
        StructField("poa46", StringType(), True),
        StructField("poa47", StringType(), True),
        StructField("poa48", StringType(), True),
        StructField("poa49", StringType(), True),
        StructField("poa50", StringType(), True),
        StructField("icd_flag", StringType(), True),
        StructField("patient_zip", StringType(), True),
        StructField("patient_id", StringType(), True),
        StructField("fac_bill_type_code", StringType(), True),
    ]
)


# list of columns to be combined into an array
RATIO9_DROPPED_COLS = (
    "ratio1", "ratio2", "ratio3", "ratio4", "ratio5", "ratio6", "ratio7", "ratio8",
    "ratio9", "ratio10", "ratio11", "ratio12", "ratio13", "ratio14", "ratio15", "ratio16",
    "ratio17", "ratio18", "ratio19", "ratio20", "ratio21", "ratio22", "ratio23", "ratio24",
    "ratio25", "ratio26", "ratio27", "ratio28", "ratio29", "ratio30", "ratio31", "ratio32",
    "ratio33", "ratio34", "ratio35", "ratio36", "ratio37",
    "dratio1", "dratio2", "dratio3", "dratio4", "dratio5", "dratio6", "dratio7",
    "dratio8", "dratio9", "dratio10", "dratio11", "dratio12", "dratio13", "dratio14", "dratio15",
    "dratio16", "dratio17", "dratio18", "dratio19", "dratio20", "dratio21", "dratio22", "dratio23",
    "dratio24", "dratio25", "dratio26", "dratio27", "dratio28", "dratio29", "dratio30", "dratio31",
    "dratio32", "dratio33", "dratio34", "dratio35", "dratio36", "dratio37"
)


# list of unused and unnecessary columns. they will be removed.
HE_DROPPED_COLS = (
    "TS", "TestCaseName", "type", "age_in_years", "age_in_months", "age_in_days",
    "birth_date", "sex", "discharge_status", "admit_date", "los", "birth_weight",
    "prin_payer", "race", "admit_type", "dx1", "dx2", "dx3", "dx4", "dx5", "dx6",
    "dx7", "dx8", "dx9", "dx10", "dx11", "dx12", "dx13", "dx14", "dx15", "dx16",
    "dx17", "dx18", "dx19", "dx20", "dx21", "dx22", "dx23", "dx24", "dx25", "dx26", "dx27",
    "dx28", "dx29", "dx30", "dx31", "dx32", "dx33", "dx34", "dx35", "dx36", "dx37", "dx38",
    "dx39", "dx40", "dx41", "dx42", "dx43", "dx44", "dx45", "dx46", "dx47", "dx48", "dx49",
    "dx50", "proc1", "proc2", "proc3", "proc4", "proc5", "proc6", "proc7", "proc8", "proc9",
    "proc10", "proc11", "proc12", "proc13", "proc14", "proc15", "proc16", "proc17",
    "proc18", "proc19", "proc20", "proc21", "proc22", "proc23", "proc24", "proc25",
    "proc26", "proc27", "proc28", "proc29", "proc30", "proc31", "proc32", "proc33",
    "proc34", "proc35", "proc36", "proc37", "proc38", "proc39", "proc40", "proc41",
    "proc42", "proc43", "proc44", "proc45", "proc46", "proc47", "proc48", "proc49",
    "proc50", "proc1_date", "proc2_date", "proc3_date", "proc4_date", "proc5_date",
    "proc6_date", "proc7_date", "proc8_date", "proc9_date", "proc10_date", "proc11_date",
    "proc12_date", "proc13_date", "proc14_date", "proc15_date", "proc16_date",
    "proc17_date", "proc18_date", "proc19_date", "proc20_date", "proc21_date",
    "proc22_date", "proc23_date", "proc24_date", "proc25_date", "proc26_date",
    "proc27_date", "proc28_date", "proc29_date", "proc30_date", "proc31_date",
    "proc32_date", "proc33_date", "proc34_date", "proc35_date", "proc36_date",
    "proc37_date", "proc38_date", "proc39_date", "proc40_date", "proc41_date",
    "proc42_date", "proc43_date", "proc44_date", "proc45_date", "proc46_date",
    "proc47_date", "proc48_date", "proc49_date", "proc50_date", "total_chg", "admit_source",
    "ed_obs_flag", "chg1", "chg2", "chg3", "chg4", "chg5", "chg6", "chg7", "chg8", "chg9",
    "chg10", "chg11", "chg12", "chg13", "chg14", "chg15", "chg16", "chg17", "chg18",
    "chg19", "chg20", "chg21", "chg22", "chg23", "chg24", "chg25", "chg26", "chg27",
    "chg28", "chg29", "chg30", "chg31", "chg32", "chg33", "chg34", "chg35", "chg36",
    "chg37", "chg38", "chg39", "chg40", "chg41", "chg42", "chg43", "chg44", "chg45",
    "chg46", "chg47", "chg48", "chg49", "chg50", "rev_code1", "rev_code2", "rev_code3",
    "rev_code4", "rev_code5", "rev_code6", "rev_code7", "rev_code8", "rev_code9",
    "rev_code10", "rev_code11", "rev_code12", "rev_code13", "rev_code14", "rev_code15",
    "rev_code16", "rev_code17", "rev_code18", "rev_code19", "rev_code20", "rev_code21",
    "rev_code22", "rev_code23", "rev_code24", "rev_code25", "rev_code26", "rev_code27",
    "rev_code28", "rev_code29", "rev_code30", "rev_code31", "rev_code32", "rev_code33",
    "rev_code34", "rev_code35", "rev_code36", "rev_code37", "rev_code38", "rev_code39",
    "rev_code40", "rev_code41", "rev_code42", "rev_code43", "rev_code44", "rev_code45",
    "rev_code46", "rev_code47", "rev_code48", "rev_code49", "rev_code50", "poa1", "poa2",
    "poa3", "poa4", "poa5", "poa6", "poa7", "poa8", "poa9", "poa10", "poa11", "poa12",
    "poa13", "poa14", "poa15", "poa16", "poa17", "poa18", "poa19", "poa20", "poa21",
    "poa22", "poa23", "poa24", "poa25", "poa26", "poa27", "poa28", "poa29", "poa30",
    "poa31", "poa32", "poa33", "poa34", "poa35", "poa36", "poa37", "poa38", "poa39",
    "poa40", "poa41", "poa42", "poa43", "poa44", "poa45", "poa46", "poa47", "poa48",
    "poa49", "poa50", "icd_flag", "patient_zip", "fac_bill_type_code",
)
